// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByLlY1Vfedy2bL1YmXD0HHS0wV3rMdd7E',
    appId: '1:490855182070:web:4d943097a6d01dabe546d7',
    messagingSenderId: '490855182070',
    projectId: 'nomadlander-livestyle',
    authDomain: 'nomadlander-livestyle.firebaseapp.com',
    storageBucket: 'nomadlander-livestyle.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK6HKbGskwIgBGoejINv5_aKWTmDeNBxU',
    appId: '1:490855182070:android:f5251375fb8dca5de546d7',
    messagingSenderId: '490855182070',
    projectId: 'nomadlander-livestyle',
    storageBucket: 'nomadlander-livestyle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0nx0zrmpZm0oU_ReysknaAwgW-s9ONXQ',
    appId: '1:490855182070:ios:7cafba26475ae696e546d7',
    messagingSenderId: '490855182070',
    projectId: 'nomadlander-livestyle',
    storageBucket: 'nomadlander-livestyle.firebasestorage.app',
    iosBundleId: 'com.example.flutterlive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0nx0zrmpZm0oU_ReysknaAwgW-s9ONXQ',
    appId: '1:490855182070:ios:7cafba26475ae696e546d7',
    messagingSenderId: '490855182070',
    projectId: 'nomadlander-livestyle',
    storageBucket: 'nomadlander-livestyle.firebasestorage.app',
    iosBundleId: 'com.example.flutterlive',
  );

}